  NET_CORE_APP_60="latest"
  NET_CORE_APP_60_SHA="latest"
  NET_CORE_APP_80="latest"
  NET_CORE_APP_80_SHA="latest"
  NET_CORE_APP_90="latest"
  NET_CORE_APP_90_SHA="latest"
  NODE18VERSION="latest"
  NODE20VERSION="latest"
  PHP81VERSION="latest"
  PHP81VERSION_SHA="latest"
  PHP82VERSION="latest"
  PHP82VERSION_SHA="latest"
  PHP83VERSION="latest"
  PHP83VERSION_SHA="latest"
  PYTHON310VERSION="latest"
  PYTHON311VERSION="latest"
  PYTHON312VERSION="latest"
  PYTHON38VERSION="latest"
  PYTHON39VERSION="latest"

  export NET_CORE_APP_60
  export NET_CORE_APP_60_SHA
  export NET_CORE_APP_80
  export NET_CORE_APP_80_SHA
  export NET_CORE_APP_90
  export NET_CORE_APP_90_SHA
  export NODE18VERSION
  export NODE20VERSION
  export PHP81VERSION
  export PHP81VERSION_SHA
  export PHP82VERSION
  export PHP82VERSION_SHA
  export PHP83VERSION
  export PHP83VERSION_SHA
  export PYTHON310VERSION
  export PYTHON311VERSION
  export PYTHON312VERSION
  export PYTHON38VERSION
  export PYTHON39VERSION