parameters:
  agentName: ''

jobs:
- job: Cleaning_${{ parameters.agentName }}
  displayName: ${{ parameters.agentName }}
  pool:
    name: OryxLinux
    demands:
    - agent.name -equals ${{ parameters.agentName }}
  timeoutInMinutes: 30
  steps:
  - template: _cleanImageCacheTemplate.yml
