parameters:
  displayName: ''
  imageDir: ''
  imageType: ''
  scriptPath: ''
  artifactsFileName: ''
  jobName: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  timeoutInMinutes: 250
  steps:
  - template: _cleanImageCacheTemplate.yml

  - task: ShellScript@2
    displayName: Build images
    inputs:
      scriptPath: ${{ parameters.scriptPath }}
      args: ${{ parameters.imageDir }} ${{ parameters.imageType }}

  - task: CopyFiles@2
    displayName: Copy artifacts to staging directory
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/artifacts'
      contents: '**/*.*'
      targetFolder: $(Build.ArtifactStagingDirectory)
      overWrite: true
    condition: true

  - task: Docker@1
    displayName: Push built base images to dev ACR
    inputs:
      command: push
      azureSubscriptionEndpoint: $(ascName)
      azureContainerRegistry: $(acrName)
      pushMultipleImages: true
      imageNamesPath: '$(Build.ArtifactStagingDirectory)/images/${{ parameters.artifactsFileName }}'
      enforceDockerNamingConvention: false

  - task: ShellScript@2
    displayName: 'Clean up Docker containers and images'
    inputs:
      scriptPath: ./vsts/scripts/cleanDocker.sh

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)

  - task: ShellScript@2
    displayName: 'Clean up Docker containers and images'
    inputs:
      scriptPath: ./vsts/scripts/cleanDocker.sh
    condition: true
