jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  timeoutInMinutes: 250
  templateContext:
    outputs:
    - output: pipelineArtifact
      displayName: 'Publish build artifacts'
      targetPath: $(Build.ArtifactStagingDirectory)
  steps:
  - task: ShellScript@2
    displayName: Build images
    inputs:
      scriptPath: ${{ parameters.scriptPath }}
      args: ${{ parameters.imageDir }} ${{ parameters.imageDebianFlavor }}
    env:
      ORYX_SDK_STORAGE_ACCOUNT_ACCESS_TOKEN: $(ORYX-SDK-STAGING-PRIVATE-SAS-TOKEN)
      DOTNET_PRIVATE_STORAGE_ACCOUNT_ACCESS_TOKEN: $(DotnetPrivateStorageAccountAccessToken)
  - task: CopyFiles@2
    displayName: Copy artifacts to staging directory
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/artifacts'
      contents: '**/*.*'
      targetFolder: $(Build.ArtifactStagingDirectory)
      overWrite: true
    condition: true
  - task: 1ES.PushContainerImage@1
    displayName: Push built base images to dev ACR
    inputs:
      image: '$(Build.ArtifactStagingDirectory)/images/${{ parameters.artifactsFileName }}'
      remoteImage: $(acrname)/$(Build.ArtifactStagingDirectory)/images/${{ parameters.artifactsFileName }}
  - task: ShellScript@2
    displayName: 'Clean up Docker containers and images'
    inputs:
      scriptPath: ./vsts/scripts/cleanDocker.sh
  - task: ShellScript@2
    displayName: 'Clean up Docker containers and images'
    inputs:
      scriptPath: ./vsts/scripts/cleanDocker.sh
    condition: true