parameters:
  displayName: ''
  imageDir: ''
  imageDebianFlavor: ''
  scriptPath: ''
  artifactsFileName: ''
  jobName: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  timeoutInMinutes: 250
  steps:  
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection - OSS Compliance'
    inputs:
      ignoreDirectories: '$(Build.SourcesDirectory)/tests'

  - task: ShellScript@2
    displayName: Build images
    inputs:
      scriptPath: ${{ parameters.scriptPath }}
      args: ${{ parameters.imageDir }} ${{ parameters.imageDebianFlavor }}

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: Generate Software Bill of Materials (SBOM)
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)'
      PackageName: 'Visual Studio 2022'
      PackageVersion: '17.0.2'

  - task: CopyFiles@2
    displayName: Copy artifacts to staging directory
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/artifacts'
      contents: '**/*.*'
      targetFolder: $(Build.ArtifactStagingDirectory)
      overWrite: true
    condition: true

  - task: Docker@1
    displayName: Push built base images to dev ACR
    inputs:
      command: push
      azureSubscriptionEndpoint: $(ascName)
      azureContainerRegistry: $(acrName)
      pushMultipleImages: true
      imageNamesPath: '$(Build.ArtifactStagingDirectory)/images/${{ parameters.artifactsFileName }}'
      enforceDockerNamingConvention: false

  - task: ShellScript@2
    displayName: 'Clean up Docker containers and images'
    inputs:
      scriptPath: ./vsts/scripts/cleanDocker.sh

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)

  - task: ShellScript@2
    displayName: 'Clean up Docker containers and images'
    inputs:
      scriptPath: ./vsts/scripts/cleanDocker.sh
    condition: true
