parameters:
- name: storageAccountUrl
  type: string
  default: https://oryxsdksstaging.blob.core.windows.net
jobs:
- template: /vsts/pipelines/templates/integrationTests/_pythonIntegrationJobTemplate.yml@self
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}
- template: /vsts/pipelines/templates/integrationTests/_dotnetcoreIntegrationJobTemplate.yml@self
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}
- template: /vsts/pipelines/templates/integrationTests/_nodeIntegrationJobTemplate.yml@self
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}
- template: /vsts/pipelines/templates/integrationTests/_phpIntegrationJobTemplate.yml@self
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}