parameters:
  - name: storageAccountUrl
    type: string
    default: https://oryxsdksdev.blob.core.windows.net
  - name: pythonVersions
    type: object
    default:
      - '3.7'
      - '3.8'
      - '3.9'
      - '3.10'
      - '3.11'
  - name: dotNetCoreVersions
    type: object
    default:
      - '3.0'
      - '3.1'
      - '5.0'
      - '6.0'
      - 'dynamic'
      - 'runtime'
  - name: nodeVersions
    type: object
    default:
      - '14'
      - '14-3'
      - '14-4'
      - '14-5'
      - '14-6'
      - '14-8'
      - '14-9'
      - '14-10'
      - '14-11'
      - '16'
  - name: golangVersions
    type: object
    default:
      - '1.17'
      - '1.18'
      - '1.19'
  - name: phpVersions
    type: object
    default:
      - '7.4'
      - '8.0'
      - '8.1'

jobs:
# Python integration tests
- ${{ each pythonVersion in parameters.pythonVersions }}:
  - template: templates/integrationTests/_pythonIntegrationJobTemplate.yml
      parameters:
        storageAccountUrl: ${{ parameters.storageAccountUrl }}
        version: ${{ pythonVersion }}

# DotNetCore integration tests
- ${{ each dotNetCoreVersion in parameters.dotNetCoreVersions }}:
  - template: templates/integrationTests/_dotnetcoreIntegrationJobTemplate.yml
      parameters:
        storageAccountUrl: ${{ parameters.storageAccountUrl }}
        version: ${{ dotNetCoreVersion }}

# NodeJS integration tests
- ${{ each nodeVersion in parameters.nodeVersions }}:
  - template: templates/integrationTests/_nodeIntegrationJobTemplate.yml
      parameters:
        storageAccountUrl: ${{ parameters.storageAccountUrl }}
        version: ${{ nodeVersion }}

# Golang integration tests
- ${{ each golangVersion in parameters.golangVersions }}:
  - template: templates/integrationTests/_golangIntegrationJobTemplate.yml
      parameters:
        storageAccountUrl: ${{ parameters.storageAccountUrl }}
        version: ${{ golangVersion }}

# PHP integration tests
- ${{ each phpVersion in parameters.phpVersions }}:
  - template: templates/integrationTests/_phpIntegrationJobTemplate.yml
      parameters:
        storageAccountUrl: ${{ parameters.storageAccountUrl }}
        version: ${{ phpVersion }}

# Database integration tests
- template: templates/integrationTests/_dbIntegrationJobTemplate.yml
    parameters:
      storageAccountUrl: ${{ parameters.storageAccountUrl }}

- job: Job_DevStorageAccountTest
  displayName: Test Dev Storage Account
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1.x'
    inputs:
      version: 3.1.x
  - task: ShellScript@2
    displayName: 'Test Dev storage account'
    env:
      ORYX_TEST_SDK_STORAGE_URL: ${{ parameters.storageAccountUrl }}
    inputs:
      scriptPath: ./build/testIntegration.sh
      args: StorageAccountTests=Dev