jobs:
- job: Job_PythonIntegrationTests
  displayName: Run Python Integration Tests
  dependsOn:
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  timeoutInMinutes: 100
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=python"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _setReleaseTag.yml
  - template: _buildTemplate.yml

- job: Job_DotNetCoreIntegrationTests
  displayName: Run DotNetCore Integration Tests
  dependsOn:
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=dotnetcore"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _setReleaseTag.yml
  - template: _buildTemplate.yml

- job: Job_NodeIntegrationTests
  displayName: Run NodeJs Integration Tests
  dependsOn:
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  variables:
    skipComponentGovernanceDetection: true
  timeoutInMinutes: 300
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=node"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _setReleaseTag.yml
  - template: _buildTemplate.yml

- job: Job_PhpIntegrationTests
  displayName: Run Php Integration Tests
  dependsOn:
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=php"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _setReleaseTag.yml
  - template: _buildTemplate.yml

- job: Job_DbIntegrationTests
  displayName: Run Database Integration Tests
  dependsOn:
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=db"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _setReleaseTag.yml
  - template: _buildTemplate.yml