jobs:
- job: Release_PhpBuildBaseImage
  displayName: Push PHP Build Base Image to MCR
  pool:
    name: OryxLinux
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'php-build'

- job: Release_PhpRuntimeBaseImage
  displayName: Push PHP Runtime Base Image to MCR
  pool:
    name: OryxLinux
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'php'

- job: Release_DotNetCoreRuntimeBaseImage
  displayName: Push DotNetCore Runtime Base Images to MCR
  pool:
    name: OryxLinux
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'dotnetcore'

- job: Release_PythonBaseImage
  displayName: Push Python Build Base Image to MCR
  pool:
    name: OryxLinux
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'python-build'

- job: Release_NodeBaseImage
  displayName: Push Node Base Image to MCR
  pool:
    name: OryxLinux
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'node'

- job: Release_YarnCacheBuildBaseImage
  displayName: Push Yarn Cache Build Base Image to MCR
  pool:
    name: OryxLinux
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'yarn-cache-build'