jobs:
- job: Release_BuildImage
  displayName: Push Build Image to MCR and DockerHub
  pool:
    name: OryxLinux
  variables:
    skipComponentGovernanceDetection: true

  steps:
  - script: |
      echo "##vso[task.setvariable variable=ReleaseBuildImages;]true"
      echo "##vso[task.setvariable variable=ReleaseRuntimeImages;]false"
    displayName: 'Set variables'
      
  - template: _releaseStepTemplate.yml

- job: Release_RuntimeImages
  displayName: Push Runtime Images to MCR and DockerHub
  pool:
    name: OryxLinux
  variables:
    skipComponentGovernanceDetection: true

  steps:
  - script: |
      echo "##vso[task.setvariable variable=ReleaseBuildImages;]false"
      echo "##vso[task.setvariable variable=ReleaseRuntimeImages;]true"
    displayName: 'Set variables'
      
  - template: _releaseStepTemplate.yml