// This file was auto-generated from 'constants.yaml'. Changes may be overridden.

package consts

const EnvironmentType string = "ORYX_ENV_TYPE"
const ApplicationInsightsConnectionStringEnvVarName string = "ORYX_AI_CONNECTION_STRING"
const AppServiceAppNameEnvVarName string = "APPSETTING_WEBSITE_SITE_NAME"
const ScmCommitIdEnvVarName string = "SCM_COMMIT_ID"
const PhpOrigin string = "PHP_ORIGIN"
const PhpFpmConfigurationFile string = "/usr/local/etc/php-fpm.d/www.conf"
const PhpFpmMaxChildrenEnvVarName string = "FPM_MAX_CHILDREN"
const PhpFpmStartServersEnvVarName string = "FPM_START_SERVERS"
const PhpFpmMinSpareServersEnvVarName string = "FPM_MIN_SPARE_SERVERS"
const PhpFpmMaxSpareServersEnvVarName string = "FPM_MAX_SPARE_SERVERS"
const PhpFpmMaxChildrenSettingName string = "pm.max_children"
const PhpFpmStartServersSettingName string = "pm.start_servers"
const PhpFpmMinSpareServersSettingName string = "pm.min_spare_servers"
const PhpFpmMaxSpareServersSettingName string = "pm.max_spare_servers"
const DebianFlavor string = "DEBIAN_FLAVOR"
const UserAppInsightsKeyEnv string = "APPINSIGHTS_INSTRUMENTATIONKEY"
const UserAppInsightsAgentExtensionVersion string = "ApplicationInsightsAgent_EXTENSION_VERSION"
const UserAppInsightsConnectionStringEnv string = "APPLICATIONINSIGHTS_CONNECTION_STRING"
const UserDotnetAiVersion string = "2.8.42"
const UserDotnetStartupHooks string = "/DotNetCoreAgent/2.8.42/StartupHook/Microsoft.ApplicationInsights.StartupHook.dll"
const UserNetcoreHostingstartupAssemblies string = "Microsoft.ApplicationInsights.StartupBootstrapper"
const PythonEnableGunicornMultiWorkersEnvVarName string = "PYTHON_ENABLE_GUNICORN_MULTIWORKERS"
const PythonGunicornConfigPathEnvVarName string = "PYTHON_USE_GUNICORN_CONFIG_FROM_PATH"
const PythonGunicornCustomWorkerNum string = "PYTHON_GUNICORN_CUSTOM_WORKER_NUM"
const PythonGunicornCustomThreadNum string = "PYTHON_GUNICORN_CUSTOM_THREAD_NUM"
const NginxConfFile string = "NGINX_CONF_FILE"
