parameters:
  - name: storageAccountUrl
    type: string
    default: https://oryxsdksstaging.blob.core.windows.net

jobs:
# Python integration tests
- template: integrationTests/_pythonIntegrationJobTemplate.yml
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}

# DotNetCore integration tests
- template: integrationTests/_dotnetcoreIntegrationJobTemplate.yml
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}

# NodeJS integration tests
- template: integrationTests/_nodeIntegrationJobTemplate.yml
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}

# PHP integration tests
- template: integrationTests/_phpIntegrationJobTemplate.yml
  parameters:
    storageAccountUrl: ${{ parameters.storageAccountUrl }}