# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
  id = "oryx/buildpack"
  version = "0.0.4"

# Stacks that the buildpack will work with
[[stacks]]
  id = "oryx.stacks.skeleton"