#!/bin/sh
set -e

dir=/usr/src/php

usage() {
	echo "usage: $0 COMMAND"
	echo
	echo "Commands:"
	echo "   extract  extract PHP source into $dir."
	echo "   delete   delete PHP source from $dir."
}

case "$1" in
	extract)
		mkdir -p "$dir"
		if [ ! -f "$dir/.docker-extracted" ]; then
			tar -Jxf /usr/src/php.tar.xz -C "$dir" --strip-components=1
			touch "$dir/.docker-extracted"
		fi
		;;
	delete)
		rm -rf "$dir"
		;;
	*)
		usage
		exit 1
		;;
esac
