variables:
- group: Oryx
- name: ascName
  value: oryx-automation-service-principal
- name: acrName
  value: oryxdevmcr.azurecr.io
- name: skipComponentGovernanceDetection
  value: true
- name: Packaging.EnableSBOMSigning
  value: true

jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php buster runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php-fpm
    imageDebianFlavor: buster
    artifactsFileName: php-fpm-runtimeimage-bases-buster.txt
    jobName: Build_PHP_FPM_Buster_Base

- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php bullseye runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php-fpm
    imageDebianFlavor: bullseye
    artifactsFileName: php-fpm-runtimeimage-bases-bullseye.txt
    jobName: Build_PHP_Fpm_Bullseye_Base

- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php bookworm runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php-fpm
    imageDebianFlavor: bookworm
    artifactsFileName: php-fpm-runtimeimage-bases-bookworm.txt
    jobName: Build_PHP_Fpm_Bookworm_Base

- job: Release_PhpRuntimeBaseImage
  dependsOn: 
    - Build_Php_Fpm_Buster_Base
    - Build_PHP_Fpm_Bullseye_Base
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'php-fpm'
