variables:
    ascName: oryxSP
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
    Packaging.EnableSBOMSigning: true

jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php stretch runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php-fpm
    imageDebianFlavor: stretch
    artifactsFileName: php-fpm-runtimeimage-bases-stretch.txt
    jobName: Build_Php_Fpm_Base

- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php buster runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php-fpm
    imageDebianFlavor: buster
    artifactsFileName: php-fpm-runtimeimage-bases-buster.txt
    jobName: Build_PHP_FPM_Buster_Base

- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php bullseye runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php-fpm
    imageDebianFlavor: bullseye
    artifactsFileName: php-fpm-runtimeimage-bases-bullseye.txt
    jobName: Build_PHP_FPM_Bullseye_Base

- job: Release_PhpRuntimeBaseImage
  dependsOn: 
    - Build_Php_Fpm_Base
    - Build_Php_Fpm_Buster_Base
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'php-fpm'
