variables:
    ascName: oryxSP
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
    Packaging.EnableSBOMSigning: true

jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php runtime buster base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php
    imageDebianFlavor: buster
    artifactsFileName: php-runtimeimage-bases-buster.txt
    jobName: Build_Buster_BaseImages

- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php runtime bullseye base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php
    imageDebianFlavor: bullseye
    artifactsFileName: php-runtimeimage-bases-bullseye.txt
    jobName: Build_Bullseye_BaseImages

- job: Release_PhpRuntimeBaseImage
  dependsOn: 
    - Build_Buster_BaseImages
    - Build_Bullseye_BaseImages
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'php'
