variables:
    ascName: oryxSP
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
    Packaging.EnableSBOMSigning: true
  
jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build python runtime bullseye base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: python
    imageDebianFlavor: bullseye
    artifactsFileName: python-runtimeimage-bases-bullseye.txt
    jobName: Build_Bullseye_BaseImages

- job: Release_PythonRuntimeBaseImage
  dependsOn: 
    - Build_Bullseye_BaseImages
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'python'
