variables:
    ascName: OryxMCR
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
  
jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build ruby runtime stretch base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: ruby
    imageDebianFlavor: stretch
    artifactsFileName: ruby-runtimeimage-bases-stretch.txt
    jobName: Build_Ruby_Stretch_BaseImages

- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build ruby runtime buster base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: ruby
    imageDebianFlavor: buster
    artifactsFileName: ruby-runtimeimage-bases-buster.txt
    jobName: Build_Ruby_Buster_BaseImages

- job: Release_RubypRuntimeBaseImage
  dependsOn: 
    - Build__Ruby_Stretch_BaseImages
    - Build_Ruby_Buster_BaseImages
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: OryxLinux
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'ruby'
