variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io

queue:
  name: OryxLinux

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/build/python
    - build/
    - vsts/

steps:
- task: Docker@1
  displayName: Build prerequisites
  inputs:
    command: build
    dockerFile: images/build/python/prereqs/Dockerfile
    useDefaultContext: false
    buildContext: $(Build.Repository.LocalPath)
    imageName: python-build-prereqs

- task: Docker@1
  displayName: Build Python 2.7
  inputs:
    command: build
    dockerFile: images/build/python/2.7/Dockerfile
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python27-build
    includeLatestTag: true
- task: Docker@1
  displayName: Push Python 2.7
  inputs:
    command: push
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python27-build

- task: Docker@1
  displayName: Build Python 3.5
  inputs:
    command: build
    dockerFile: images/build/python/3.5/Dockerfile
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python35-build
    includeLatestTag: true
- task: Docker@1
  displayName: Push Python 3.5
  inputs:
    command: push
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python35-build

- task: Docker@1
  displayName: Build Python 3.6
  inputs:
    command: build
    dockerFile: images/build/python/3.6/Dockerfile
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python36-build
    includeLatestTag: true
- task: Docker@1
  displayName: Push Python 3.6
  inputs:
    command: push
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python36-build

- task: Docker@1
  displayName: Build Python 3.7
  inputs:
    command: build
    dockerFile: images/build/python/3.7/Dockerfile
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python37-build
    includeLatestTag: true
- task: Docker@1
  displayName: Push Python 3.7
  inputs:
    command: push
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    imageName: python37-build
