parameters:
  name: ''
  displayName: ''
  imageDir: ''


jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  steps:

  - task: ShellScript@2
    displayName: Build images
    inputs:
      scriptPath: ./build/build-buildimage-bases.sh
      args: ${{ parameters.imageDir }}

  - task: CopyFiles@2
    displayName: Copy artifacts to staging directory
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/artifacts'
      contents: '**/*.*'
      targetFolder: $(Build.ArtifactStagingDirectory)
      overWrite: true
    condition: true

  - task: Docker@1
    displayName: Push built images to dev ACR
    inputs:
      command: push
      azureSubscriptionEndpoint: $(ascName)
      azureContainerRegistry: $(acrName)
      pushMultipleImages: true

  - task: ShellScript@2
    displayName: 'Clean up Docker containers and images'
    inputs:
      scriptPath: ./vsts/scripts/dockerCleanup.sh
      imageNamesPath: '$(Build.ArtifactStagingDirectory)/images/build-image-bases/${{ parameters.imageDir }}.txt'

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
