variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io
  skipComponentGovernanceDetection: true

jobs:

- template: _buildimage-bases.job-template.yml
  parameters:
    imageDir: python
    displayName: Build and push Python base images

- template: _buildimage-bases.job-template.yml
  parameters:
    imageDir: php
    displayName: Build and push PHP base images

- template: _buildimage-bases.job-template.yml
  parameters:
    imageDir: yarn-cache
    displayName: Build and push Yarn Cache base image

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/build/python
    - images/build/php
    - images/build/yarn-cache
    - build/
    - vsts/
