variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io

queue:
  name: OryxLinux

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/build/python
    - build/
    - vsts/

steps:

- task: ShellScript@2
  displayName: Build base images
  inputs:
    scriptPath: ./build/build-buildimage-bases.sh

- task: Docker@1
  displayName: Push built images to dev ACR
  inputs:
    command: push
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    pushMultipleImages: true
    imageNamesPath: '$(Build.ArtifactStagingDirectory)/images/build-image-bases.txt'

- task: CopyFiles@2
  displayName: 'Copy artifacts from source repo to agent artifacts folder'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/artifacts'
    contents: '**/*.*'
    targetFolder: $(Build.ArtifactStagingDirectory)
    overWrite: true
  condition: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
