variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io
  skipComponentGovernanceDetection: true

jobs:
- template: templates/_buildimage-bases.job-template.yml
  parameters:
    displayName: Build and push Node base images for runtime
    scriptPath: ./build/build-runtimeimages-bases.sh
    imageDir: node
    artifactsFileName: node-runtimeimage-bases.txt

- template: templates/_buildimage-bases.job-template.yml
  parameters:
    displayName: Build and push Python base images for build
    scriptPath: ./build/build-buildimage-bases.sh
    imageDir: python
    artifactsFileName: python-buildimage-bases.txt

- template: templates/_buildimage-bases.job-template.yml
  parameters:
    displayName: Build and push PHP base images for build
    scriptPath: ./build/build-buildimage-bases.sh
    imageDir: php
    artifactsFileName: php-buildimage-bases.txt

- template: templates/_buildimage-bases.job-template.yml
  parameters:
    displayName: Build and push PHP base images for runtime
    scriptPath: ./build/build-runtimeimages-bases.sh
    imageDir: php
    artifactsFileName: php-runtimeimage-bases.txt

- template: templates/_buildimage-bases.job-template.yml
  parameters:
    displayName: Build and push Yarn Cache base image
    scriptPath: ./build/build-buildimage-bases.sh
    imageDir: yarn-cache
    artifactsFileName: yarn-cache-buildimage-bases.txt

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/runtime/node
    - images/build/python
    - images/build/php
    - images/runtime/php
    - images/build/yarn-cache
    - build/
    - vsts/
