variables:
- group: Oryx

parameters:
- name: destinationStorageAccountName
  displayName: Destination Storage Account Name
  type: string
  default: oryxsdksdev
- name: dryRun
  displayName: Dry Run?
  type: boolean
  default: true

jobs:
    - job: CreateReleaseTag
      pool:
        name: AzurePipelines-EO
        demands:
          - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
      steps:
      - checkout: self
        clean: true

      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection - OSS Compliance'
        inputs:
          ignoreDirectories: '$(Build.SourcesDirectory)/tests'

      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 3.1.x'
        inputs:
          version: 3.1.x

      - task: ShellScript@2
        displayName: 'Copy SDKs from the prod storage account to a destination storage account'
        env:
          DEV_STORAGE_SAS_TOKEN: $(DEV-STORAGE-SAS-TOKEN)
          SANDBOX_STORAGE_SAS_TOKEN: $(SANDBOX-STORAGE-SAS-TOKEN)
          PROD_STORAGE_SAS_TOKEN: $(PROD-STORAGE-SAS-TOKEN)
          PERSONAL_STORAGE_SAS_TOKEN: $(${{ upper(parameters.destinationStorageAccountName) }}-PERSONAL-STORAGE-SAS-TOKEN)
        inputs:
          scriptPath: ./vsts/scripts/copySdksFromProdToStorageAccount.sh
          args:  ${{ parameters.destinationStorageAccountName }} ${{ parameters.dryRun }}

trigger: none
pr: none
