resources:
- repo: self
  fetchDepth: 15

variables:
- group: Oryx

jobs:
- job: Job_Security
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: templates/_securityChecks.yml

- job: Job_BuildImage
  displayName: Build and Test Build Image
  dependsOn: Job_Security
  condition: succeeded()
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushBuildImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

- job: Job_RuntimeImages
  displayName: Build and Test Runtime Images
  dependsOn: Job_Security
  condition: succeeded()
  pool:
    name: OryxLinux
  # Building runtime images can take a long time due our PHP images
  timeoutInMinutes: 100
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

- template: templates/_integrationJobTemplate.yml

trigger: none