parameters:
  - name: storageAccountUrl
    displayName: SDK storage account URL for testing
    type: string
    default: https://oryxsdksstaging.blob.core.windows.net
  - name: buildImages
    type: object
    default:
      -
        key: Latest
        value: latest
      -
        key: LtsVersions
        value: ltsversions
      -
        key: Jamstack
        value: jamstack
      -
        key: GithubActions
        value: githubactions
      -
        key: VsoFocal
        value: vso-focal
      -
        key: VsoBullseye
        value: vso-bullseye
      -
        key: Full
        value: full
      -
        key: Cli
        value: cli-stretch
      -
        key: CliBuster
        value: cli-buster
      -
        key: CliBullseye
        value: cli-bullseye
      -
        key: CliBuilderBullseye
        value: cli-builder-bullseye
      -
        key: Buildpack
        value: buildpack

resources:
- repo: self
  fetchDepth: 15

variables:
  group: Oryx
  Packaging.EnableSBOMSigning: true

stages:
  - stage: CreateReleaseTag
    jobs:
    - job: CreateReleaseTag
      pool:
        name: AzurePipelines-EO
        demands:
          - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
      variables:
        skipComponentGovernanceDetection: true
      steps:
      - task: ShellScript@2
        inputs:
          scriptPath: ./vsts/scripts/createReleaseTag.sh
        displayName: 'Create release tag'
      - script: |
          set -ex
          sourcesArtifactsDir="$(Build.SourcesDirectory)/artifacts"
          mkdir -p "$sourcesArtifactsDir"
          echo "$(RELEASE_TAG_NAME)" > "$sourcesArtifactsDir/releaseTag.txt"
        displayName: 'Write release tag name to an artifact file'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifact file having the release tag name'
        inputs:
          targetPath: $(Build.SourcesDirectory)/artifacts/releaseTag.txt
          artifactName: releaseTag

  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Job_Security
      displayName: Security
      condition: succeeded()
      pool:
        name: Azure Pipelines
        vmImage: windows-2022
      steps:
      - template: templates/_securityChecks.yml

      # Job loop for BuildImages
    - ${{ each buildImage in parameters.buildImages }}:
        - job: Job_BuildImage_${{ buildImage.key }}
          displayName: 'Build & Test ${{ buildImage.key }} Build image'
          pool:
            name: AzurePipelines-EO
            demands:
              - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
          timeoutInMinutes: 480
          steps:
          - script: |
              echo "##vso[task.setvariable variable=BuildBuildImages;]true"
              echo "##vso[task.setvariable variable=TestBuildImages;]true"
              echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
              echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
              echo "##vso[task.setvariable variable=PushBuildImages;]true"
              echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
              echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
              echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
              echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
              if [[ "${{ buildImage.value }}" =~ "cli-builder" ]]; then
                echo "##vso[task.setvariable variable=PushBuilderImages;]true"
              fi
            displayName: 'Set variables'
          - template: templates/_buildTemplate.yml
            parameters:
                imageType: ${{ buildImage.value }}

    - job: Job_Buster_RuntimeImages
      displayName: Build and Test Buster Runtime Images
      condition: succeeded()
      pool:
        name: AzurePipelines-EO
        demands:
          - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
      # Building runtime images can take a long time due to our PHP images
      timeoutInMinutes: 480
      steps:
      - script: |
          echo "##vso[task.setvariable variable=BuildBuildImages;]false"
          echo "##vso[task.setvariable variable=TestBuildImages;]false"
          echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
          echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
          echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
          echo "##vso[task.setvariable variable=PushBuildImages;]false"
          echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
          echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
          echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
        displayName: 'Set variables'
      - template: templates/_buildTemplate.yml
        parameters:
            imageType: buster

    - job: Job_Bullseye_RuntimeImages
      displayName: Build and Test Bullseye Runtime Images
      condition: succeeded()
      pool:
        name: AzurePipelines-EO
        demands:
          - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
      # Building runtime images can take a long time due to our PHP images
      timeoutInMinutes: 480
      steps:
      - script: |
          echo "##vso[task.setvariable variable=BuildBuildImages;]false"
          echo "##vso[task.setvariable variable=TestBuildImages;]false"
          echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
          echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
          echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
          echo "##vso[task.setvariable variable=PushBuildImages;]false"
          echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
          echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
          echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
        displayName: 'Set variables'
      - template: templates/_buildTemplate.yml
        parameters:
            imageType: bullseye

    - job: Job_Bookworm_RuntimeImages
      displayName: Build and Test Bookworm Runtime Images
      condition: succeeded()
      pool:
        name: AzurePipelines-EO
        demands:
          - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
      # Building runtime images can take a long time due to our PHP images
      timeoutInMinutes: 480
      steps:
      - script: |
          echo "##vso[task.setvariable variable=BuildBuildImages;]false"
          echo "##vso[task.setvariable variable=TestBuildImages;]false"
          echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
          echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
          echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
          echo "##vso[task.setvariable variable=PushBuildImages;]false"
          echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
          echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
          echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
        displayName: 'Set variables'
      - template: templates/_buildTemplate.yml
        parameters:
            imageType: bookworm

    - template: templates/_integrationJobTemplate.yml
      parameters:
        storageAccountUrl: ${{ parameters.storageAccountUrl }}

    - job: Job_StagingStorageAccountTest
      displayName: Test Staging Storage Account
      pool:
        name: AzurePipelines-EO
        demands:
          - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
      variables:
        skipComponentGovernanceDetection: true
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 7.x'
        inputs:
          version: 7.0.306

      - task: ShellScript@2
        displayName: 'Test staging storage account'
        env:
          ORYX_TEST_SDK_STORAGE_URL: ${{ parameters.storageAccountUrl }}
          ORYX_SDK_STORAGE_ACCOUNT_ACCESS_TOKEN: $(ORYX-SDK-STAGING-PRIVATE-SAS-TOKEN)
        inputs:
          scriptPath: ./build/testIntegration.sh
          args: StorageAccountTests=Staging

trigger: none