variables:
  - group: Oryx

stages:
- stage: Build
  jobs:
  - job: Python
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'python'

  - job: Php
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'

  - job: Node
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'

  - job: DotNetCore
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'dotnet'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: OryxLinux
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Artifacts'
      inputs:
        artifactName: drop

    - task: AzureCLI@1
      displayName: Upload files to Azure Storage
      inputs:
        azureSubscription: oryxSP
        scriptPath: ./vsts/scripts/publishFilesToAzureStorage.sh
        arguments: oryxsdksdev
       
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/build/python
    - images/build/php
    - images/build/dotnet
    - images/build/node
    - build/
    - vsts/