variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io

queue:
  name: OryxLinux

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/build/python
    - build/
    - vsts/

steps:
- task: ShellScript@2
  displayName: Build base images
  inputs:
    scriptPath: ./build/build-buildimage-bases.sh

- task: Docker@1
  displayName: Push built images to dev ACR
  inputs:
    command: push
    azureSubscriptionEndpoint: $(ascName)
    azureContainerRegistry: $(acrName)
    pushMultipleImages: true
    imageNamesPath: '$(Build.ArtifactStagingDirectory)/images/build-image-bases.txt'
