resources:
- repo: self
  fetchDepth: 15
jobs:
- job: Job_1
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- job: Job_2
  displayName: Build and Sign Oryx
  condition: succeeded()
  pool:
    name: VSEng-MicroBuildVS2017
    demands:
    - msbuild
    - visualstudio

  variables:
    SignType: 'test'

  steps:
  - template: _signbinary.yml

- job: Job_3
  displayName: Build and Publish Oryx Images
  dependsOn: Job_2
  condition: succeeded()
  pool:
    name: OryxLinux
    demands: sh
  steps:
  - template: _buildTemplateWithSign.yml

trigger: none
