resources:
- repo: self
  fetchDepth: 15

variables:
- group: Oryx

jobs:
- job: runCfsPackageAnalysis
  displayName: Validating Packages
  steps:
  - task: Package-Ingestion@0
    inputs:
      terrapinApiTokens: 'Ingestion Task Tokens-DevDiv'

- job: Job_Security
  displayName: Security
  pool:
    name: Hosted VS2017
  steps:
  - template: templates/_securityChecks.yml

- job: Job_BuildImage
  displayName: Build and Test Build Images
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

- job: Job_RuntimeImages
  displayName: Build and Test Runtime Images
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

trigger: none