parameters:
  - name: storageAccountUrl
    displayName: SDK storage account URL for testing
    type: string
    default: https://oryxsdksstaging.blob.core.windows.net
  - name: buildImages
    type: object
    default:
      - 
        key: Latest
        value: latest
      - 
        key: LtsVersions
        value: ltsversions
      - 
        key: Jamstack
        value: jamstack
      - 
        key: GithubActions
        value: githubactions
      - 
        key: VsoFocal
        value: vso-focal
      - 
        key: VsoBullseye
        value: vso-bullseye
      - 
        key: Full
        value: full
      - 
        key: Cli
        value: cli-stretch
      - 
        key: CliBuster
        value: cli-buster
      -
        key: CliBullseye
        value: cli-bullseye
      - 
        key: CliBuilderBullseye
        value: cli-builder-bullseye
      - 
        key: Buildpack
        value: buildpack

resources:
- repo: self
  fetchDepth: 15

variables:
  group: Oryx
  Packaging.EnableSBOMSigning: true

jobs:
- job: Job_Security
  displayName: Security
  pool:
    name: Azure Pipelines
    vmImage: windows-2022
  steps:
  - template: templates/_securityChecks.yml

- ${{ each buildImage in parameters.buildImages }}:
  - job: Job_BuildImage_${{ buildImage.key }}
    displayName: Build and Test Build ${{ buildImage.key }} Image
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    variables:
    - group: Oryx
    timeoutInMinutes: 480
    steps:
    - script: |
        echo "##vso[task.setvariable variable=BuildBuildImages;]true"
        echo "##vso[task.setvariable variable=TestBuildImages;]true"
        echo "##vso[task.setvariable variable=PushBuildImages;]false"
        echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
        echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
        echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
        echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
        if [[ "${{ buildImage.value }}" =~ "cli-builder" ]]; then
          echo "##vso[task.setvariable variable=PushBuilderImages;]true"
        fi
      displayName: 'Set variables'
    - template: templates/_buildTemplate.yml
      parameters:
          imageType: ${{ buildImage.value }}

- job: Job_BuilderImages
  displayName: Build Builder Images
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  timeoutInMinutes: 480
  steps:
  - template: templates/_builderTemplate.yml
  dependsOn: Job_BuildImage_CliBuilderBullseye

- job: Job_Buster_RuntimeImages
  displayName: Build and Test Buster Runtime Images
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  variables:
  - group: Oryx
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
        echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml
    parameters:
        imageType: buster

- job: Job_Bullseye_RuntimeImages
  displayName: Build and Test Bullseye Runtime Images
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  variables:
  - group: Oryx
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
        echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml
    parameters:
        imageType: bullseye

- job: Job_Bookworm_RuntimeImages
  displayName: Build and Test Bookworm Runtime Images
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  variables:
  - group: Oryx
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
        echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml
    parameters:
        imageType: bookworm
        
trigger: none