parameters:
  - name: storageAccountUrl
    displayName: Storage Account Url
    type: string
    default: https://oryxsdksdev.blob.core.windows.net
  - name: buildImages
    type: object
    default:
      - 
        key: Latest
        value: latest
      - 
        key: LtsVersions
        value: ltsversions
      - 
        key: Jamstack
        value: jamstack
      - 
        key: GithubActions
        value: githubactions
      - 
        key: VsoFocal
        value: vso-focal
      - 
        key: Full
        value: full
      - 
        key: Cli
        value: cli
      - 
        key: CliBuster
        value: cli-buster
      - 
        key: Buildpack
        value: buildpack

resources:
- repo: self
  fetchDepth: 15

variables:
  group: Oryx
  Packaging.EnableSBOMSigning: true

jobs:
- job: Job_Security
  displayName: Security
  pool:
    name: Azure Pipelines
    vmImage: windows-2022
  steps:
  - template: templates/_securityChecks.yml

- ${{ each buildImage in parameters.buildImages }}:
  - job: Job_BuildImage_${{ buildImage.key }}
    displayName: Build and Test Build ${{ buildImage.key }} Image
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    timeoutInMinutes: 480
    steps:
    - script: |
        echo "##vso[task.setvariable variable=BuildBuildImages;]true"
        echo "##vso[task.setvariable variable=TestBuildImages;]true"
        echo "##vso[task.setvariable variable=PushBuildImages;]false"
        echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
        echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
        echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
      displayName: 'Set variables'
    - template: templates/_buildTemplate.yml
      parameters:
          imageType: ${{ buildImage.value }}
          storageAccountUrl: ${{ storageAccountUrl }}

- job: Job_RuntimeImages
  displayName: Build and Test Runtime Images
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml
    parameters:
        storageAccountUrl: ${{ storageAccountUrl }}

trigger: none