# specify with `--build-arg "runtime-version"`
# available runtimes listed at https://hub.docker.com/u/oryxprod
ARG RUNTIME=node:10.14

FROM mcr.microsoft.com/oryx/build:latest as build
WORKDIR /app
COPY . .
RUN oryx build /app

FROM mcr.microsoft.com/oryx/${RUNTIME}
COPY --from=build /app /app
RUN cd /app && oryx
ENTRYPOINT ["/app/run.sh"]