parameters:
- name: poolName
  displayName: Pool Name
  type: string
  default: Azure Pipelines
  values:
  - Azure Pipelines
- name: agentName
  displayName: Agent Name
  type: string

variables:
  skipComponentGovernanceDetection: true

stages:
- stage: CleanAgents
  displayName: Clean Oryx Agents
  jobs:
  - template: templates/_agentCleanUpJobTemplate.yml
    parameters:
      agentName: ${{ parameters.agentName }}
      poolName: ${{ parameters.poolName }}
      
# trigger is set using vsts UI, cleanup build will run every sundays 10 PM PST/PDT
trigger: none