queue:
  name: OryxLinux

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/build/
    - src/
    - build/
    - vsts/

steps:
- script: |
    echo "##vso[task.setvariable variable=BuildBuildImages]true"
    echo "##vso[task.setvariable variable=TestBuildImages]true"
    echo "##vso[task.setvariable variable=PushBuildImages]true"
    echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
  displayName: 'Set variables'

- template: _buildTemplate.yml
