// --------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// --------------------------------------------------------------------------------------------
namespace Microsoft.Oryx.BuildScriptGenerator
{
    public class BuildScriptGeneratorOptions
    {
        /// <summary>
        /// The path to the directory containing source code.
        /// </summary>
        public string SourceCodeFolder { get; set; }
        
        /// <summary>
        /// The path to the directory which will act as an intermediate directory for building the source code before
        /// the output is finally put into <see cref="OutputFolder"/>.
        /// </summary>
        public string IntermediateFolder { get; set; }

        /// <summary>
        /// The path to the directory containing the final output of building the source code.
        /// </summary>
        public string OutputFolder { get; set; }

        /// <summary>
        /// The path to the file which is going to have the generated script. Can be <c>null</c>. If <c>null</c>, the
        /// script is created in a temporary folder.
        /// </summary>
        public string ScriptPath { get; set; }

        /// <summary>
        /// Flag which indicates that a build should not happen and only a script needs to be generated.
        /// </summary>
        public bool ScriptOnly { get; set; }

        /// <summary>
        /// The name of the language that the code in <see cref="SourceCodeFolder"/> has.
        /// </summary>
        public string LanguageName { get; set; }

        /// <summary>
        /// The version of the language that the code in <see cref="SourceCodeFolder"/> has.
        /// </summary>
        public string LanguageVersion { get; set; }

        /// <summary>
        /// The temporary directory under which all temporary files generated by this tool are put in.
        /// </summary>
        public string TempDirectory { get; set; }
    }
}