parameters:
  - name: storageAccountUrl
    type: string
    default: https://oryxsdksstaging.blob.core.windows.net
  - name: testMappings
    type: object
    default:
      - category: '3.0'
        buildTag: 'debian-stretch'
      - category: '3.1'
        buildTag: 'debian-stretch'
      - category: '3.1'
        buildTag: 'github-actions-debian-stretch'
      - category: '5.0'
        buildTag: 'debian-stretch'
      - category: '5.0'
        buildTag: 'github-actions-debian-stretch'
      - category: '6.0'
        buildTag: 'debian-stretch'
      - category: '6.0'
        buildTag: 'github-actions-debian-stretch'
      - category: '7.0'
        buildTag: 'github-actions-debian-buster'
      - category: '8.0'
        buildTag: 'github-actions-debian-bookworm'
      - category: 'dynamic'
        buildTag: 'debian-stretch'
      - category: 'dynamic'
        buildTag: 'github-actions-debian-stretch'
  
jobs:
- ${{ each mapping in parameters.testMappings }}:
  - job:
    displayName: 'Run .NET Core ${{ mapping.category }} Integration Tests using build image tag ${{ mapping.buildTag }}'
    dependsOn:
    - Job_BuildImage_Latest
    - Job_BuildImage_GithubActions
    - Job_Buster_RuntimeImages
    - Job_Bullseye_RuntimeImages
    - Job_Bookworm_RuntimeImages
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    variables:
      skipComponentGovernanceDetection: true
    timeoutInMinutes: 300
    steps:
        - script: |
            echo "##vso[task.setvariable variable=BuildBuildImages;]false"
            echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
            echo "##vso[task.setvariable variable=TestBuildImages;]false"
            echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
            echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=dotnetcore-${{ mapping.category }}&build-image=${{ mapping.buildTag }}"
            echo "##vso[task.setvariable variable=TestIntegration;]true"
            echo "##vso[task.setvariable variable=PushBuildImages;]false"
            echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
            echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
            echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
          displayName: 'Set variables'
        - template: ../_setReleaseTag.yml
        - template: ../_buildTemplate.yml