parameters:
  - name: storageAccountUrl
    type: string
    default: https://oryxsdksstaging.blob.core.windows.net
  - name: testMappings
    type: object
    default:
      - category: '14-stretch-1'
        buildTag: 'debian-stretch'
      - category: '14-stretch-2'
        buildTag: 'debian-stretch'
      - category: '14-stretch-3'
        buildTag: 'debian-stretch'
      - category: '14-stretch-4'
        buildTag: 'debian-stretch'
      - category: '14-gh-buster'
        buildTag: 'github-actions-debian-buster'
      - category: '16'
        buildTag: 'debian-stretch'
      - category: '16-nuxt'
        buildTag: 'debian-stretch'
      - category: '18'
        buildTag: 'github-actions-debian-bullseye'

jobs:
- ${{ each mapping in parameters.testMappings }}:
  - job:
    displayName: 'Run Node ${{ mapping.category }} Integration Tests using build image tag ${{ mapping.buildTag }}'
    dependsOn:
    - Job_BuildImage_Latest
    - Job_BuildImage_GithubActions
    - Job_RuntimeImages
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    variables:
      skipComponentGovernanceDetection: true
    timeoutInMinutes: 300
    steps:
        - script: |
            echo "##vso[task.setvariable variable=BuildBuildImages;]false"
            echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
            echo "##vso[task.setvariable variable=TestBuildImages;]false"
            echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
            echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=node-${{ mapping.category }}&build-image=${{ mapping.buildTag }}"
            echo "##vso[task.setvariable variable=TestIntegration;]true"
            echo "##vso[task.setvariable variable=PushBuildImages;]false"
            echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
            echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
            echo "##vso[task.setvariable variable=storageAccountUrl;]${{ parameters.storageAccountUrl }}"
          displayName: 'Set variables'
        - template: ../_setReleaseTag.yml
        - template: ../_buildTemplate.yml