variables:
- group: Oryx
parameters:
- name: destinationStorageAccountName
  displayName: Destination Storage Account Name
  type: string
  default: oryxsdksstaging
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - platforms/golang
    - vsts/PlatformBinaries/golang.yml
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: AzurePipelinesUbuntu20.04compliant
      os: linux
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: Build
      jobs:
      - job: Golang_Bullseye
        timeoutInMinutes: 250
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish build artifacts'
            condition: true
            targetPath: $(Build.ArtifactStagingDirectory)
        steps:
        - template: /vsts/pipelines/templates/_platformBinariesTemplate.yml@self
          parameters:
            platformName: 'golang'
            debianFlavor: 'bullseye'
            destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
      - job: Golang_Buster
        timeoutInMinutes: 250
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish build artifacts'
            condition: true
            targetPath: $(Build.ArtifactStagingDirectory)
        steps:
        - template: /vsts/pipelines/templates/_platformBinariesTemplate.yml@self
          parameters:
            platformName: 'golang'
            debianFlavor: 'buster'
            destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
      - job: Golang_Stretch
        timeoutInMinutes: 250
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish build artifacts'
            condition: true
            targetPath: $(Build.ArtifactStagingDirectory)
        steps:
        - template: /vsts/pipelines/templates/_platformBinariesTemplate.yml@self
          parameters:
            platformName: 'golang'
            debianFlavor: 'stretch'
            destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
      - job: Golang_Ubuntu
        timeoutInMinutes: 250
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish build artifacts'
            condition: true
            targetPath: $(Build.ArtifactStagingDirectory)
        steps:
        - template: /vsts/pipelines/templates/_platformBinariesTemplate.yml@self
          parameters:
            platformName: 'golang'
            debianFlavor: 'focal-scm'
            destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
    - stage: Release
      dependsOn: Build
      jobs:
      - job: Publish_Platform_Binaries
        timeoutInMinutes: 250
        displayName: Publish to Azure Blob Storage
        steps:
        - template: /vsts/pipelines/templates/_platformBinariesReleaseTemplate.yml@self
          parameters:
            destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'