variables:
  - group: Oryx

parameters:
- name: destinationStorageAccountName
  displayName: Destination Storage Account Name
  type: string
  default: oryxsdksstaging

stages:
- stage: Build
  jobs:
  - job: Node_Bookworm
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'bookworm'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
  
  - job: Node_Bullseye
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'bullseye'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Node_Buster
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'buster'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Node_Stretch
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'stretch'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
  
  - job: Node_Ubuntu
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'focal-scm'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml
      parameters:
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - platforms/nodejs
    - vsts/PlatformBinaries/node.yml