variables:
  - group: Oryx

stages:
- stage: Build
  jobs:
  - job: Node
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - *
    include:
    - platforms/nodejs
    - vsts/PlatformBinaries/node.yml