variables:
  - group: Oryx

stages:
- stage: Build
  jobs:
  - job: Node_Buster
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'buster'

  - job: Node_Stretch
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'stretch'
  
  - job: Node_Ubuntu
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'nodejs'
        debianFlavor: 'focal-scm'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - /*
    include:
    - platforms/nodejs
    - vsts/PlatformBinaries/node.yml