variables:
  - group: Oryx

parameters:
- name: destinationStorageAccountName
  displayName: Destination Storage Account Name
  type: string
  default: oryxsdksstaging

stages:
- stage: Build
  jobs:
  - job: Php_Bookworm_SDK 
    timeoutInMinutes: 1440
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'
        debianFlavor: 'bookworm'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Php_Bullseye_SDK 
    timeoutInMinutes: 1440
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'
        debianFlavor: 'bullseye'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  
  - job: Php_Buster_SDK 
    timeoutInMinutes: 1440
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'
        debianFlavor: 'buster'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml
      parameters:
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - platforms/php
    - vsts/PlatformBinaries/php.yml