variables:
  - group: Oryx

stages:
- stage: Build
  jobs:
  - job: Php_Bullseye_SDK 
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'
        debianFlavor: 'bullseye'
  
  - job: Php_Stretch_SDK 
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'
        debianFlavor: 'stretch'
  
  - job: Php_Buster_SDK 
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'
        debianFlavor: 'buster'
  
  - job: Php_Ubuntu_SDK
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'php'
        debianFlavor: 'focal-scm'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - platforms/php
    - vsts/PlatformBinaries/php.yml