variables:
  - group: Oryx

parameters:
- name: destinationStorageAccountName
  displayName: Destination Storage Account Name
  type: string
  default: oryxsdksstaging

stages:
- stage: Build
  jobs:
  - job: Python_Bullseye_SDK
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'python'
        debianFlavor: 'bullseye'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Python_Buster_SDK
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'python'
        debianFlavor: 'buster'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Python_Stretch_SDK
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'python'
        debianFlavor: 'stretch'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Python_Ubuntu_SDK
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'python'
        debianFlavor: 'focal-scm'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml
      parameters:
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - platforms/python
    - vsts/PlatformBinaries/python.yml