variables:
  - group: Oryx

stages:
- stage: Build
  jobs:
  - job: Python_Stretch_SDK
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'python'
        debianFlavor: 'stretch'

  - job: Python_Ubuntu_SDK
    timeoutInMinutes: 250
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'python'
        debianFlavor: 'focal-scm'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: OryxLinux
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - /*
    include:
    - platforms/python
    - vsts/PlatformBinaries/python.yml