variables:
  - group: Oryx

parameters:
- name: destinationStorageAccountName
  displayName: Destination Storage Account Name
  type: string
  default: oryxsdksdev
  
stages:
- stage: Build
  jobs:
  - job: Ruby_Bullseye
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'ruby'
        debianFlavor: 'bullseye'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Ruby_Buster
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'ruby'
        debianFlavor: 'buster'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

  - job: Ruby_Stretch
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'ruby'
        debianFlavor: 'stretch'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
  
  - job: Ruby_Ubuntu
    timeoutInMinutes: 250
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesTemplate.yml
      parameters:
        platformName: 'ruby'
        debianFlavor: 'focal-scm'
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'

- stage: Release
  dependsOn: Build
  jobs:
  - job: Publish_Platform_Binaries
    timeoutInMinutes: 250
    displayName: Publish to Azure Blob Storage
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    steps:
    - template: ../templates/_platformBinariesReleaseTemplate.yml
      parameters:
        destinationSdkStorageAccountName: '${{ parameters.destinationStorageAccountName }}'
  
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - platforms/ruby
    - vsts/PlatformBinaries/ruby.yml