[[buildpacks]]
image = "mcr.microsoft.com/oryx/builder:buildpack-20230208.1"

# Order used for detection
[[order]]
    [[order.group]]
    id = "oryx/buildpack"
    version = "0.0.4"

# Stack that will be used by the builder
[stack]
id = "oryx.stacks.skeleton"
# This image is used at runtime
run-image = "mcr.microsoft.com/oryx/builder:stack-run-20230208.1"
# This image is used at build-time
build-image = "mcr.microsoft.com/oryx/builder:stack-build-20230208.1"