[[buildpacks]]
image = "%ORYX_BUILDPACK_IMAGE%"

# Order used for detection
[[order]]
    [[order.group]]
    id = "oryx/buildpack"
    version = "%ORYX_BUILDPACK_VERSION%"

# Stack that will be used by the builder
[stack]
id = "oryx.stacks.skeleton"
# This image is used at runtime
run-image = "%ORYX_RUN_STACK_IMAGE%"
# This image is used at build-time
build-image = "%ORYX_BUILD_STACK_IMAGE%"