name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch name'
        required: true
      PRdescription:
        description: 'Branch name'
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch-name }}
          base: 'user/vchintalapat/monitor-versions'
          title: "Automated PR from ${{ github.event.inputs.branch-name }}"
          body: "${{ github.event.inputs.PRdescription }}"
